### ISSUE TITLE
App crashed on production

### ISSUE THREAD

**Issue by abdoerrahiem** [TheWidlarzGroup/rn-emoji-keyboard#55]
My app force closing on production when click on button to show the emoticons, but on development it works fine.

**Comment by ddikodroid** [comment]
> My app force closing on production when click on button to show the emoticons, but on development it works fine.

how can we know what makes the app crashed if you don't provide any information?

**Comment by Pranipaso** [comment]
This is the stack trace provided by the firebase crashlytics when the user clicks on button to open the emoji picker and app crash
```
Fatal Exception: java.lang.IllegalStateException: java.lang.NoSuchFieldException: fill
       at com.horcrux.svg.RenderableView.mergeProperties(RenderableView.java:93)
       at com.horcrux.svg.GroupView.drawGroup(GroupView.java:52)
       at com.horcrux.svg.GroupView.draw(GroupView.java:6)
       at com.horcrux.svg.RenderableView.render(RenderableView.java:265)
       at com.horcrux.svg.SvgView.drawChildren(SvgView.java:158)
       at com.horcrux.svg.SvgView.drawOutput(SvgView.java:71)
       at com.horcrux.svg.SvgView.onDraw(SvgView.java:16)
       at android.view.View.draw(View.java:23898)
       at android.view.View.draw(View.java:23770)
       at android.view.ViewGroup.drawChild(ViewGroup.java:5355)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:5112)
       at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:3)
       at android.view.View.draw(View.java:23768)
       at android.view.ViewGroup.drawChild(ViewGroup.java:5355)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:5112)
       at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:3)
       at android.view.View.draw(View.java:23768)
       at android.view.ViewGroup.drawChild(ViewGroup.java:5355)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:5112)
       at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:3)
       at android.view.View.draw(View.java:23768)
       at android.view.ViewGroup.drawChild(ViewGroup.java:5355)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:5112)
       at android.view.View.draw(View.java:23901)
       at android.widget.HorizontalScrollView.draw(HorizontalScrollView.java:2238)
       at com.facebook.react.views.scroll.ReactHorizontalScrollView.draw(ReactHorizontalScrollView.java:47)
       at android.view.View.draw(View.java:23770)
       at android.view.ViewGroup.drawChild(ViewGroup.java:5355)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:5112)
       at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:3)
       at android.view.View.draw(View.java:23901)
       at android.view.View.draw(View.java:23770)
       at android.view.ViewGroup.drawChild(ViewGroup.java:5355)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:5112)
       at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:3)
       at android.view.View.draw(View.java:23901)
       at android.view.View.draw(View.java:23770)
       at android.view.ViewGroup.drawChild(ViewGroup.java:5355)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:5112)
       at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:3)
       at android.view.View.draw(View.java:23768)
       at android.view.ViewGroup.drawChild(ViewGroup.java:5355)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:5112)
       at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:3)
       at android.view.View.draw(View.java:23768)
       at android.view.ViewGroup.drawChild(ViewGroup.java:5355)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:5112)
       at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:3)
       at android.view.View.draw(View.java:23768)
       at android.view.ViewGroup.drawChild(ViewGroup.java:5355)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:5112)
       at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:3)
       at android.view.View.draw(View.java:23901)
       at android.view.View.draw(View.java:23770)
       at android.view.ViewGroup.drawChild(ViewGroup.java:5355)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:5112)
       at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:3)
       at android.view.View.draw(View.java:23768)
       at android.view.ViewGroup.drawChild(ViewGroup.java:5355)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:5112)
       at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:3)
       at android.view.View.draw(View.java:23768)
       at android.view.ViewGroup.drawChild(ViewGroup.java:5355)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:5112)
       at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:3)
       at android.view.View.draw(View.java:23768)
       at android.view.ViewGroup.drawChild(ViewGroup.java:5355)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:5112)
       at android.view.View.draw(View.java:23768)
       at android.view.ViewGroup.drawChild(ViewGroup.java:5355)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:5112)
       at android.view.View.draw(View.java:23768)
       at android.view.ViewGroup.drawChild(ViewGroup.java:5355)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:5112)
       at android.view.View.draw(View.java:23768)
       at android.view.ViewGroup.drawChild(ViewGroup.java:5355)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:5112)
       at android.view.View.draw(View.java:23901)
       at com.android.internal.policy.DecorView.draw(DecorView.java:1378)
       at android.view.ViewRootImpl.drawSoftware(ViewRootImpl.java:5573)
       at android.view.ViewRootImpl.draw(ViewRootImpl.java:5481)
       at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:5148)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:4212)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2919)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:10491)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1108)
       at android.view.Choreographer.doCallbacks(Choreographer.java:866)
       at android.view.Choreographer.doFrame(Choreographer.java:797)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1092)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:226)
       at android.os.Looper.loop(Looper.java:313)
       at android.app.ActivityThread.main(ActivityThread.java:8669)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
```

**Comment by mateki0** [comment]
Unfortunately I couldn't reproduce this bug, but I can see a soLoader error in your logs.

`
E/SoLoader: couldn't find DSO to load: libjscexecutor.so caused by: dlopen failed: library "libjsc.so" not found: needed by /data/app/~~SafeEBijzzIf_y95_VRt7A==/com.a4free-
`

Can you try some of the solutions from this thread? 
https://github.com/facebook/react-native/issues/25537

**Comment by jakex7** [comment]
Hi, unfortunately I'm closing this issue due to inactivity and, as @mateki0 said we couldn't reproduce this bug, so it's probably not related to the library. If the same problem persists, feel free to reopen.

**Comment by jakex7** [comment]
@abdoerrahiem @Pranipaso You can also try this, maybe it will work for you https://github.com/TheWidlarzGroup/rn-emoji-keyboard/issues/82#issuecomment-1236261672
